### ISSUE TITLE
Add callback on Stop

### ISSUE THREAD

**Issue by goyometeojorito** [jhuckaby/webcamjs#103]
If stop the webcam with the browser, the script can't detect.

![webcam](https://cloud.githubusercontent.com/assets/13981294/9493450/e26290f2-4bff-11e5-9a88-4ec88760fd35.png)

It would be nice to have a callback to know when it happens
How do I detect?

**Comment by jhuckaby** [comment]
Apologies, but I don't think there is a way to do it.  Note that ONLY Firefox allows you to stop the camera with browser controls, and when you do, no events seem to be emitted on the `MediaStream` object.  You are free to access this object to inspect it yourself:

`Webcam.stream`

Chrome seems to support some events on the object, but as I stated above I can't seem to stop the camera in Chrome.  Firefox seems to have none of these properties:

<img width="353" alt="screenshot 2015-08-26 09 22 43" src="https://cloud.githubusercontent.com/assets/700765/9499468/7d8b39fc-4bd4-11e5-83e7-e036f7e5530b.png">

Sorry I could not be of any help, but good luck to you!
