### ISSUE TITLE
grayscale option

### ISSUE THREAD

**Issue by ruffrey** [jhuckaby/webcamjs#113]
It would be great to be able to do grayscale images. I have considered adding it and doing a PR, but first - would you accept this?

**Comment by positlabs** [comment]
I don't think this needs to be part of webcamjs. There a ton of other post-processing libs out there already.

**Comment by positlabs** [comment]
I didn't mean to totally discourage it. I'm not the maintainer of webcamjs. I just wanted to put my opinion out there.

**Comment by jhuckaby** [comment]
I agree with @positlabs, but note that you can easily achieve this using the existing API.  Just grab a reference to the underlying Canvas object after capture, and the raw pixels are all yours to manipulate.

```javascript
Webcam.snap( function(data_uri, canvas, context) {
	var imageData = context.getImageData(0, 0, canvas.width, canvas.height);
	var data = imageData.data;
	for (var i = 0; i < data.length; i += 4) {
		var brightness = 0.34 * data[i] + 0.5 * data[i + 1] + 0.16 * data[i + 2];
		data[i] = brightness;
		data[i + 1] = brightness;
		data[i + 2] = brightness;
	}
	context.putImageData(imageData, 0, 0);
} );
```
