### ISSUE TITLE
How to access the stream object in the flash fallback mode?

### ISSUE THREAD

**Issue by KrishnaPG** [jhuckaby/webcamjs#118]
I am trying to hook the stream object to webrtc (so that the camera content is captured locally but displayed elsewhere on the web).

The html5 api looks like is having a valid 'stream' object. But for the flash fallback, how to access the stream object ?

**Comment by jhuckaby** [comment]
Hey @KrishnaPG, I'm so sorry to tell you this, but Flash has no stream object.  The only thing we can do is grab still image frames from the Flash movie.

**Comment by KrishnaPG** [comment]
Thank you @jhuckaby 

How to capture the images from the flash. Is it this method `Webcam.snap()`? Does it automatically take care of capturing the content for both webcam api and flash ?

**Comment by jhuckaby** [comment]
Yes, that is exactly correct.

**Comment by KrishnaPG** [comment]
Thanks @jhuckaby
