### ISSUE TITLE
getUserMedia is deprecated

### ISSUE THREAD

**Issue by NscAdmin** [jhuckaby/webcamjs#121]
The library is using getUserMedia which is deprecated when can this be replaced?

**Comment by MattyBalaam** [comment]
I assume the console error I get relates to this? 

navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

**Comment by jhuckaby** [comment]
Ugh, they keep changing everything on me!  Don't worry, I'll get this fixed soon.  Thanks for reporting it!  Leaving this issue open.

**Comment by jhuckaby** [comment]
Released v1.0.5 with a fix for this.  Thanks guys!

https://github.com/jhuckaby/webcamjs/releases/tag/v1.0.5

\- Joe
