### ISSUE TITLE
navigator.mediaDevices cannot be overridden on Chrome 48.

### ISSUE THREAD

**Issue by SpartanJ** [jhuckaby/webcamjs#122]
Chrome 48 has a couple of changes that break the library.
Since navigator.mediaDevices seems to be locked, the navigator.mediaDevices.getUserMedia assignation doesn't do anything and breaks the library, since navigator.mediaDevices doesn't come with the function predefined.
[fix.diff.txt](https://github.com/jhuckaby/webcamjs/files/44465/fix.diff.txt)

**Comment by jhuckaby** [comment]
All fixed, thanks for reporting this!

https://github.com/jhuckaby/webcamjs/commit/394584d9cfbfde1c247baa9597fcfcbe7fc1d476

**Comment by carlosrberto** [comment]
this release is in npm?

**Comment by jhuckaby** [comment]
It is now -- sorry for the delay.  v1.0.6 has all the latest `navigator.mediaDevices` changes.

https://github.com/jhuckaby/webcamjs/releases/tag/v1.0.6

**Comment by carlosrberto** [comment]
thanks @jhuckaby!
