### ISSUE TITLE
Webcam.reset() - camera still on after calling (Chrome)

### ISSUE THREAD

**Issue by kyleconrad** [jhuckaby/webcamjs#127]
In Chrome Version 47.0.2526.73 (64-bit) OSX, everything is working great - until I call Webcam.reset(). At that point, it SEEMS to work as expected - video gone, container emptied, etc. However, the red light in the Chrome tab is still there and my display camera is still lit up as if it is working. Even removed the container that it is attached to, no change.

**Comment by jhuckaby** [comment]
Works fine for me.  Try this demo page, let camera load, then click the reset button:

https://pixlcore.com/demos/webcamjs/demos/reset.html

Light turns off and everything.

Tested in: OS X Chrome Version 47.0.2526.73 (64-bit)

**Comment by kyleconrad** [comment]
Hm, so that works. But even changing stuff around over here, can't get my click event to make it work. Could it be because the Webcam.snap is getting fired within the same event? (Using a settimeout to delay the Webcam.reset() so they aren't simultaneous)

**Comment by kyleconrad** [comment]
Update: moved Webcam.reset() to a different on('click', function(){}) and no luck - technically it does everything (removes video, etc. etc.) except turn that little red light off.

**Comment by kyleconrad** [comment]
I'm an idiot. (As usual with bugs like this.)

I'm using a Jscii library to convert the video to ASCII characters as part of a transition, and I left the option webrtc: true on for it, which meant it was still keeping SOME stream alive, even if that stream never technically existed. Removing this option and everything works just fine.

Thanks for the help on this, sorry for being a dummy.
