### ISSUE TITLE
Webcam.on('live', function() {}); doesn't fire on Firefox

### ISSUE THREAD

**Issue by kyleconrad** [jhuckaby/webcamjs#128]
On Firefox 42.0 (OSX), the Webcam.on('live', function() {}); never seems to fire - the camera icon appears in the URL bar and the video shows up in the window just fine, so I know it's working, it just never fires the callback. This leads to issues with trying to capture an image (returns the error "Webcam.js Error: Webcam is not loaded yet").

**Comment by jhuckaby** [comment]
Works fine for me:

![screenshot 2015-12-10 09 39 25](https://cloud.githubusercontent.com/assets/700765/11723223/11467bc0-9f22-11e5-9917-410f00b42224.png)

Try this test page:

https://pixlcore.com/demos/webcamjs/demos/events.html

\- Joe

**Comment by kyleconrad** [comment]
Just tested and yeah, that works. I'm currently attaching the webcam inside an "on('click',function(){})" vs on initial page load - could this be why? I've tried putting those functions inside the function as well as outside, neither work on FF (but work fine on Chrome when placed outside).

**Comment by jhuckaby** [comment]
Make sure you register your `live` event listener before you call `attach()`.  With getUserMedia the two things can happen in the same thread, so there may be a race condition here.

**Comment by kyleconrad** [comment]
Yup, even tried

    Webcam.set({
        width: 1280,
        height: 720
    });
    Webcam.on('load', function() {
        alert('test');
    });
    Webcam.on('live', function() {
        alert('test');
    });

before any click functions, just to see if that was causing it, and neither one of those fires at any point (even when the camera is live).

**Comment by kyleconrad** [comment]
Note: these both work just fine when Webcam.attach('#cam-preview'); is taken out of the click function.

**Comment by jhuckaby** [comment]
Here is a test page which demonstrates all the features you need.  It (1) doesn't attach the webcam until you click a button, (2) captures and displays the `live` event on the right side of the page, and (3) calls `reset()` after snapping a pic, which correctly shuts down the camera (my camera light turns off).  Tested on latest Chrome and Firefox.

https://pixlcore.com/demos/webcamjs/demos/click-live-snap-reset-test.html

Can you possibly view the source of this page and figure out what is different in your app?

**Comment by kyleconrad** [comment]
Wow. Yup. This worked just fine and got my code working as well based off it.

Basically, moving Webcam.attach('#cam-preview') into a separate function (camSetup()) and then calling camSetup() from the click works. Calling the attach from the click itself doesn't. Super weird but that seems to do the trick.

Thanks so much for the help on this one.

**Comment by jhuckaby** [comment]
No prob, glad you got it working!
