### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by borisreitman** [jhuckaby/webcamjs#136]
I have forked the project to provide upload support using flash. You can take a look at my commits.

https://github.com/borisreitman/webcamjs

I also deleted the Webcam.fla because I am not sure if I have to change it if I make changes to the sources. The command line compilation method is sufficient.

**Comment by jhuckaby** [comment]
Hey, this is great!  Good work, man!  I'm really surprised you put in all this effort for a dying browser that only has 2% market share.  I applaud you!

I'll link to your fork from the docs, in the section that talks about how to handle upload in older browsers.

**Comment by borisreitman** [comment]
I just have a requirement at work to support IE9. I am not sure how many IE9 users are, because it is hard to trust online stats. But it is a fact that Vista where IE9 is default is going to be supported for another year by Microsoft. In fact, we are dropping support for IE10, but keeping IE9. How funny is that?
