### ISSUE TITLE
How to check if there is no webcam, then no alert?

### ISSUE THREAD

**Issue by piavgh** [jhuckaby/webcamjs#140]
Hi @jhuckaby ,

I'm working with this library, and I think it works excellently.

I have a problem, now if there is no webcam, it will show an alert "Could not access webcam". But this is very annoying, I just want it to check if there is no webcam, then hide the container (i.e #my_camera), and also hide the Capture button.

How can I do this? Is there anyway to make it without changing the webcam.js file?

Thank you very much.

**Comment by jhuckaby** [comment]
Thanks.

This is covered in the docs.  Scroll down and read the [Custom Events[(https://github.com/jhuckaby/webcamjs#custom-events) section:

> By default the error event shows a JavaScript alert dialog, but if you register your own event handler this action is suppressed, and your function is called instead.

```js
Webcam.on( 'error', function(err) {
    // an error occurred (see 'err')
} );
```

Good luck!

**Comment by mguida22** [comment]
@jhuckaby Would you accept a pull request to change the default to a `console.log` instead of `alert`? I think in most use cases this would be preferred but it's up to you

**Comment by jhuckaby** [comment]
@mguida22 Unfortunately the problem with that is most people don't check the browser console, even developers who are evaluating a new library like WebcamJS.  So they end up with a blank page with no webcam and no error visible to them, and they e-mail me or enter new issues.  The alert() was an effort to prevent this, and really allow people to see the error right in their face when it occurred.  They can of course override the behavior and put in their own error handler which completely replaces the alert.

I know that generally usage of alert() is considered bad nowadays, but it is really my hope that people will put in their own event listeners to capture errors and use their own handling code.  That way errors can be "themed" into their own site's CSS, or dialog system, etc.

**Comment by mguida22** [comment]
That makes sense to me. Thanks for working on this! You've done a great job!

**Comment by jhuckaby** [comment]
@mguida22 Thanks man!  That is very much appreciated.  Still lots of work to be done on this library, and I much appreciate the bug reports and feature requests.  Just gotta keep trying to find the time to work on it ;)
