### ISSUE TITLE
Demos not working on Firefox for Mac (v 44.0.1)

### ISSUE THREAD

**Issue by escobar5** [jhuckaby/webcamjs#149]
I cannot get the demos to work on firefox for mac. I get the following error:

Webcam.js Error: Could not access webcam: OverconstrainedError: Constraints could be not satisfied.

**Comment by positlabs** [comment]
Try setting the constraints manually. I think there is a way to pass in a constraints object that uses option instead of mandatory.

**Comment by escobar5** [comment]
Sorry, it was not webcamjs, it was a problem with my camera. Thanks
