### ISSUE TITLE
Running the basic demo locally

### ISSUE THREAD

**Issue by Gela** [jhuckaby/webcamjs#154]
This is definitely a silly question, but I can't seem to be figure out how to run the basic demo locally on my browser. I assume I don't need any backend support since it's written in Js but could anyone give me any pointers on what to look into?

Thank you

**Comment by positlabs** [comment]
You will need to run a local server. Might also need to add localhost to a
whitelist

**Comment by Gela** [comment]
Surprisingly I could run it without having to set up a local server on Firefox but Chrome is still giving me a hard time. I'll check to see if it works on a local server. Thanks.
