### ISSUE TITLE
Webcam.snap function return only data:,

### ISSUE THREAD

**Issue by saucysalamandar** [jhuckaby/webcamjs#158]
When using webcam.snap function, the returned data_uri only contains "data:,".

**Comment by nityanarayan44** [comment]
They are making this webcam lib. generic by providing data_uri,
now user will decide, what they want to do with this.

you can use this data_uri by two way (as i implemented):

1: Either you can directly use this data_uri to show this image in html '<img>' element by doing: 
    `<img id="photo" src=""></img>`
    `<script> document.getElementById('photo').src=data_uri; </script>    `

2: or you can convert this data_uri to blob object and play with this.
   by doing:

  `var blob = function() {`
		`var dataURI = data_uri; //here data_uri assumed as global scope.`
		`// convert base64/URLEncoded data component to raw binary data held in a string`
		 `var byteString;`
		`if (dataURI.split(',')[0].indexOf('base64') >= 0)`
		`     byteString = atob(dataURI.split(',')[1]);`
		`else`
		     `byteString = unescape(dataURI.split(',')[1]);`

		// separate out the mime component
		var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
		// write the bytes of the string to a typed array
		var ia = new Uint8Array(byteString.length);
		for (var i = 0; i < byteString.length; i++) {
			 ia[i] = byteString.charCodeAt(i);
	        }
		//returning new image as blob object.
		return new Blob([ia], {type:mimeString});
	}();

**Comment by KRinnNet** [comment]
Im facing the same problem, data_uri returns " **data:,** ", tried in chrome and firefox same problem, using jquery 2.2.4, bootstrap 3.3.6

**Comment by jhuckaby** [comment]
I cannot reproduce this issue in any browser.  It must have something to do with your particular webcam or webcam drivers.  Here are a few things for you to try:

- Try this HTML5 Webcam test page: https://simpl.info/getusermedia/
- Try this Flash Webcam test page: https://www.onlinemictest.com/webcam-test-in-adobe-flash
- Try jQuery Webcam: http://www.xarg.org/project/jquery-webcam-plugin/
- Try JpegCamera: https://github.com/amw/jpeg_camera

Do any of those work with your webcam?

Also, a few general tips:

- Do not run any WebcamJS demos on your local PC. Flash needs the page to be hosted on a server (with an https:// address) to access the camera.
- Make sure your camera preview size is large enough. Adobe Flash can only show its dialogs if there is enough space. 320x240 or larger.
- Disable ad blockers. Many of them block Flash.
- Disable all your browser extensions. One of them may be interfering with Flash.
- Make sure you have a working webcam with the appropriate drivers.
- Make sure Adobe Flash is up to date.

\- Joe

**Comment by KRinnNet** [comment]
Hi Joe,

It's great to hear from you.

I tried all the above websites and YES my webcam works with all of them, and the ironic thing is ALL the DEMOS WORKS too.

I have tried it even in HTTPS, I can get the webcam to display correctly, but Webcam.snap() function return the data_uri as **data:,** .

I have attached the stripped down version of my website as test.html.txt and the minified webcamjs as webcam.min.js.txt, please copy them to your local webserver and remove the .txt. Please try and let me because I tried everything but couldn't solve it.

Thank You

[test.html.txt](https://github.com/jhuckaby/webcamjs/files/310877/test.html.txt)
[webcam.min.js.txt](https://github.com/jhuckaby/webcamjs/files/310874/webcam.min.js.txt)

**Comment by KRinnNet** [comment]
Hi Joe,

I got it, forgot to set the webcam first, sorry for wasting your time.

Thank You

**Comment by jhuckaby** [comment]
No prob, glad you were able to figure it out.  I will add an explicit error for this use case.  If someone tries to `attach()` before calling `set()`, it'll throw a LOUD error :)

**Comment by jhuckaby** [comment]
This should do it:

https://github.com/jhuckaby/webcamjs/commit/05d6ed59bbebbe4a1b22db1dc0c7e10b23ad245f

Tagged 1.0.7 and published to NPM.

**Comment by ghost** [comment]
Hi again after 4 years.

 I am getting the same error as mentioned above.

My Code is:


	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.js"></script>'
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  	<div class="modal fade" id="cameraContainer" role="dialog">
		<div class="modal-dialog modal-lg">
			
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Modal Header</h4>
				</div>
				<div id="cameraPosition" class="modal-body" style="overflow:visible!important;">
				</div>
				<div class="modal-footer">
					<button type="button" id="captureImg" class="btn btn-default">Capture</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
	<script>

		$(document).ready(function () {
			
			Webcam.set({
				width: 'auto',
				height: 'auto',
				image_format: 'jpeg',
				jpeg_quality: 100,
				flip_horiz: true
			});
			$('#snapshotButton').click(function(){
				$('#cameraContainer').modal('show');

				Webcam.attach('#cameraPosition');
			});
			$('#captureImg').click(function(){
				Webcam.snap(function (data_uri) {
					$('#cameraPosition').html('<img src="' + data_uri + '"/>')
				});
			});
			$('#cameraContainer').on('hidden.bs.modal', function (e) {
				Webcam.reset();
			})

Help would be appreciated

**Comment by cihn** [comment]
still no solution to this?

**Comment by cihn** [comment]
Solution:

You should set width statically on Webcam.set
If you set width 'auto' or '100%' it will give this 'data:,' issue. 

Thank you.

**Comment by khrysnaarya012** [comment]
my webcam.snap does'nt working 
this is my code :

`</script>';
}
echo'
<script src="'.$base_url.'/mod/assets/js/sw-script.js"></script>';
if ($mod =='present'){?>
<script type="text/javascript">
   var result;
    $(document).ready(function getLocation() {
        result = document.getElementById("latitude");
       // 
        if(navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
        } else {
            swal({title: 'Oops!', text:'Maaf, browser Anda tidak mendukung geolokasi HTML5.', icon: 'error', timer: 3000,});
        }
    });
    
    // Define callback function for successful attempt
    function successCallback(position) {
       result.innerHTML =""+ position.coords.latitude + ","+position.coords.longitude + "";
    }

    // Define callback function for failed attempt
    function errorCallback(error) {
        if(error.code == 1) {
            swal({title: 'Oops!', text:'Anda telah memutuskan untuk tidak membagikan posisi Anda, tetapi tidak apa-apa. Kami tidak akan meminta Anda lagi.', icon: 'error', timer: 3000,});
        } else if(error.code == 2) {
            swal({title: 'Oops!', text:'Jaringan tidak aktif atau layanan penentuan posisi tidak dapat dijangkau.', icon: 'error', timer: 3000,});
        } else if(error.code == 3) {
            swal({title: 'Oops!', text:'Waktu percobaan habis sebelum bisa mendapatkan data lokasi.', icon: 'error', timer: 3000,});
        } else {
            swal({title: 'Oops!', text:'Waktu percobaan habis sebelum bisa mendapatkan data lokasi.', icon: 'error', timer: 3000,});
        }
    }
    
    // start webcame
    Webcam.set({
        width: 590,height: 460,
        image_format: 'jpeg',
        jpeg_quality:80,
    });

    var cameras = new Array(); //create empty array to later insert available devices
    navigator.mediaDevices.enumerateDevices() // get the available devices found in the machine
    .then(function(devices) {
        devices.forEach(function(device) {
        var i = 0;
            if(device.kind=== "videoinput"){ //filter video devices only
                cameras[i]= device.deviceId; // save the camera id's in the camera array
                i++;
            }
        });
    })

    Webcam.set('constraints',{
        width: 590,
        height: 460,
        image_format: 'jpeg',
        jpeg_quality:80,
        sourceId: cameras[0]
    });

    Webcam.attach('.webcam-capture');
    // preload shutter audio clip
    var shutter = new Audio();
    //shutter.autoplay = true;
    shutter.src = navigator.userAgent.match(/Firefox/) ? './mod/assets/js/webcamjs/shutter.ogg' : './mod/assets/js/webcamjs/shutter.mp3';
    function captureimage() {
    var latitude = $('.latitude').html();
        // play sound effect
        shutter.play();
        // take snapshot and get image data
        Webcam.snap( function(data_uri) {
            // display results in page
            Webcam.upload(data_uri, './sw-proses?action=present&latitude='+latitude+'', function(code,text) {
                $data       =''+text+'';
                var results = $data.split("/");
                $results = results[0];
                $results2 = results[1];
                if($results =='success'){
                    swal({title: 'Berhasil!', text:$results2, icon: 'success', timer: 3500,});
                    setTimeout("location.href = './';",3600);
                }else{
                    swal({title: 'Oops!', text:text, icon: 'error', timer: 3500,});
                }
            });    
        } );
    }`
