### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined line 473

### ISSUE THREAD

**Issue by aBrookland** [jhuckaby/webcamjs#159]
We're occasionally seeing the above error logged.

The stack trace is always:

```
var sty = this.container.style;   - line 473
this.unflip();                    - line 186
self.reset();                     - line 64
```

So it's the beforeunload event listener that is triggering the error.

The webcam is shown in a popup and attach() is only called when the popup is shown and reset() is called when the popup is closed.

So I think we have a situation where this.container is unset either because we never called attach() or because we've already called reset().

To stop the error I've added a check for this.container to the start of reset().

```javascript
reset: function() {
    // no need to do anything if we've never been set up or already been reset
    if (!this.container) return;
```

**Comment by jhuckaby** [comment]
Thank you!  I'll incorporate your fix into the next release.
