### ISSUE TITLE
how to rename image file name

### ISSUE THREAD

**Issue by heminp12** [jhuckaby/webcamjs#168]
its store long name in database so i required to short name for image.

**Comment by jhuckaby** [comment]
Uhhh.... the image comes across as a binary blob in the HTTP POST data.  It's basically the same as posting an HTML form with a `<input type="file" name="webcam">`.  It is up to you how to write the data to disk on your server.  Name the file however you like -- it's in your hands.  Webcam.js doesn't write any files.  Consult your HTTP library documentation for instructions.
