### ISSUE TITLE
Disable automatic white balance. RAW video

### ISSUE THREAD

**Issue by mogue** [jhuckaby/webcamjs#171]
I want the RAW unbalanced video stream from the camera, is there a way to do this via WebRTC and would you consider adding an option for this in the API?

**Comment by positlabs** [comment]
There's no way to control driver settings from WebRTC. You will have to do it via driver software, or maybe some tool like gphoto2.

**Comment by mogue** [comment]
damn w3c! thank you for the suggestions and a quick reply, webcamjs is nice.
