### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by roccomuso** [jhuckaby/webcamjs#173]
Error throwed:

    webcam.js:322 Uncaught (in promise) ReferenceError: err is not defined(…)

Referring to: https://github.com/jhuckaby/webcamjs/blob/master/webcam.js#L322

**Comment by jhuckaby** [comment]
Ugh, this is from a recent pull request from @osdiab.  I knew this was going to bite me.

https://github.com/jhuckaby/webcamjs/pull/164/files

I'll work on fixing this right away, sorry.

**Comment by roccomuso** [comment]
@jhuckaby thank you, your quick reply really appreciated ;)

**Comment by jhuckaby** [comment]
That should do it.  Let me know if v1.0.8 has any other issues!  Thanks!
