### ISSUE TITLE
Flip image

### ISSUE THREAD

**Issue by garoi** [jhuckaby/webcamjs#174]
Hi!
It's possible flipping horizontally, before upload the image?

**Comment by jhuckaby** [comment]
https://github.com/jhuckaby/webcamjs#flipping-the-image-mirror-mode

**Comment by garoi** [comment]
I have a flip in live preview, but I need unflip when upload the image. It's possible? 

Thank you

**Comment by jhuckaby** [comment]
Sorry, I didn't understand what you meant.  There is no built-in solution to this in the WebcamJS library.  If you enable the flip feature, it flips both the preview *and* the final image together.

If you want to UNFLIP the final image after capture, you can add some custom JavaScript code to manipulate the raw pixels using a HTML5 Canvas object.  Something like this may do what you want (untested):

```js
Webcam.snap( function(data_uri, canvas, context) {
    var flip_canvas = document.createElement('canvas');
    flip_canvas.width = canvas.width;
    flip_canvas.height = canvas.height;

    var flip_context = flip_canvas.getContext('2d');
    flip_context.translate(canvas.width, 0);
    flip_context.scale(-1, 1);
    flip_context.drawImage(canvas, 0, 0);

    data_uri = flip_canvas.toDataURL('image/' + Webcam.params.image_format, Webcam.params.jpeg_quality / 100 );
    // Now data_uri should have an UN-flipped image
});
```

Good luck!
