### ISSUE TITLE
Access denied from another computer

### ISSUE THREAD

**Issue by hensoft** [jhuckaby/webcamjs#179]
Access denied if i try to access from another computer, even inside the same network. Does anyone knows how to solve this?

Thanks

![access_denied](https://cloud.githubusercontent.com/assets/8502142/16460502/b08dd03a-3df5-11e6-953d-dfcbc7b5b526.PNG)

**Comment by jhuckaby** [comment]
You need to use HTTPS, even on a local LAN.  192.168.0.0/16 is not an exception to the rule.  Only 127.0.0.0/8 is.  This is explained in the docs:

## Important Note for Chrome 47+

Google Chrome has made it a strict requirement that your website be secure (HTTPS) if you want to access the camera.  This change is live in Chrome version 47 and up.  So basically, if you want to use WebcamJS, you will need to host your website with SSL / HTTPS.  The only alternative is to force Flash fallback mode on Chrome, which is probably not desirable.

See this Chromium page for details: [https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)

Note that you do not need HTTPS for localhost / 127.0.0.1.  Here is the list of rules for Chrome which unlock the camera:

| Scheme | Host | Port |
|--------|------|------|
| `https://` | `*` | `*` |
| `wss://` | `*` | `*` |
| `*` | `localhost` | `*` |
| `*` | `*.localhost` | `*` |
| `*` | `127/8` | `*` |
| `*` | `::1/128` | `*` |
| `file://` | `*` | `-` |
| `chrome-extension://` | `*` | `-` |
