### ISSUE TITLE
webcam.js not working in Chrome: Webcam is not loaded yet

### ISSUE THREAD

**Issue by mostafachatillon** [jhuckaby/webcamjs#183]
I cannot use the demo locally on Chrome. I get: Webcam is not loaded yet

On Firefox, the demo works
![webcamchrome](https://cloud.githubusercontent.com/assets/8183572/17077553/4ac6faaa-50d4-11e6-8a19-a60bcf40bf5b.png)

**Comment by mostafachatillon** [comment]
The screenshot was with chrome version: 47.0.2526.73-1
The problem remains with google-chrome-stable 
![webjschrome52](https://cloud.githubusercontent.com/assets/8183572/17077636/e194e792-50d6-11e6-81d6-47c6d21f9da4.png)
52.0.2743.82-1

**Comment by lichtamberg** [comment]
Has this been fixed? I also get the message with latest stable chrome.

**Comment by carlosrberto** [comment]
Chrome requires https to use webcam:
https://github.com/jhuckaby/webcamjs#important-note-for-chrome-47

**Comment by positlabs** [comment]
`getUserMedia` will only work on a server (e.g. localhost), and not directly from a file (e.g. file://)

**Comment by dolftax** [comment]
I'm on localhost. Still facing same error.

**Comment by positlabs** [comment]
@carlosrberto it's worth noting that it WILL work on localhost without https

**Comment by waqar2012** [comment]
Yes
Thanks for sharing information.

**Comment by positlabs** [comment]
@jhuckaby this issue can be closed. The issue was due to loading from file://

**Comment by jhuckaby** [comment]
Ah, thanks!

**Comment by juankaballero** [comment]
Buenas a mi me aparece este error y estoy trabajando en localhost. Primeface 6.0. Solo me funciona en Internet explorer

**Comment by Vish-was** [comment]
> I cannot use the demo locally on Chrome. I get: Webcam is not loaded yet
> 
> On Firefox, the demo works
> ![webcamchrome](https://cloud.githubusercontent.com/assets/8183572/17077553/4ac6faaa-50d4-11e6-8a19-a60bcf40bf5b.png)

I am also getting this

**Comment by jhuckaby** [comment]
@Vish-was WebcamJS doesn't work using local files on disk, meaning, if your URL says `file://` it will not work.  You need to host the HTML on an actual web server, so the URL reads `https://`.
