### ISSUE TITLE
Suggestion for chrome and non-ssl sites

### ISSUE THREAD

**Issue by john2014** [jhuckaby/webcamjs#184]
Problem: Starting from Chrome 47+, Google only allows  HTML5 getUserMedia for SSL site. Since many sites (or most sites) do not yet support SSL, they may not be able to load webcamjs; unless they manually force flash.

Solution: Automatically detect if browser is Chrome and site is non-ssl. If yes, then automatically force flash; so that webcamjs works "out of the box" for these users.

Here is the code which would help

`if (navigator.userAgent.match(/Chrome\D+(\d+)/))`
           ` {`
               ` if (window.location.protocol != "https:")`
                    `this.userMedia = null;`
           ` }`

Add this code on line 92 of webcam.js file (immediately after checking for Firefox version 21).

**Comment by jhuckaby** [comment]
Unfortunately it's more complicated than that.  Chrome allows for non-HTTPS access of the camera if the IP address is localhost, or *.localhost, or 127.0.0.1, or anything in the 127/8 block, or IPv6 ::1/128, etc.  So the Flash fallback check would have to honor all those rules as well.

Chrome allows the camera on the following schemes / hosts / ports:

| Scheme | Host | Port |
|--------|------|------|
| `https://` | `*` | `*` |
| `wss://` | `*` | `*` |
| `*` | `localhost` | `*` |
| `*` | `*.localhost` | `*` |
| `*` | `127/8` | `*` |
| `*` | `::1/128` | `*` |
| `file://` | `*` | `-` |
| `chrome-extension://` | `*` | `-` |

See this Chromium page for details: [https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)

It might be better to wait for user media to throw an error, then catch the error, and switch to flash mode before ultimately failing out.

That being said, I really want Flash to die, and don't really want to add anything new to the library that makes it MORE likely for it to be used.  I'd be happier if everyone simply implements HTTPS going forward 😄

**Comment by john2014** [comment]
> It might be better to wait for user media to throw an error, then catch the error, and switch to flash mode before ultimately failing out.

I like this idea. This would also make it future proof. Have you already implemented this in the webcam.js code (automatically switch to flash mode on error)? If not, could you kindly post a sample code which can do this?

Thank you :smile:

**Comment by john2014** [comment]
Also another thing that can make it future proof:

On line 76, change from

`navigator.mediaDevices : ((navigator.mozGetUserMedia || navigator.webkitGetUserMedia) `

to 

`navigator.mediaDevices : ((navigator.getUserMedia || navigator.mozGetUserMedia || navigator.webkitGetUserMedia) `

Same change on line 79. This change is from Mozilla Docs: 

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by jhuckaby** [comment]
Actually, I discovered that you cannot rely on `navigator.getUserMedia` because it was partially implemented by certain older browser versions but in a broken state.  Specifically, I found that in certain versions of Chrome, `navigator.getUserMedia` was present but broken, but `navigator.webkitGetUserMedia` worked just fine.  Go figure!  Also, `navigator.getUserMedia` has been deprecated in the future in favor of the newfangled `navigator.mediaDevices` -- so it can be safely abandoned in the future.

Preparing new version with your Flash fallback on error feature.  Should be up in a few minutes.

**Comment by jhuckaby** [comment]
Version 1.0.11 pushed -- it should do what you want.  Thanks!

**Comment by john2014** [comment]
Thanks Joseph. I looked at this commit and noticed there maybe a bug.

When falling back to flash, there maybe a possibility that flash may not be installed (or disabled) in user browser. Apple devices (ipad, iphone, etc) do NOT support flash.

In those cases it may be best to throw an error. So the best workflow would be (1) check if browser supports navigator.mediaDevices (2) If it does not, then fall back to flash (3) If it doesnt support flash, then throw error and let user know that webcam.js cannot be loaded in that browser. 

Apple devices will meet all three criteria. Their Safari browser neither support navigator.mediaDevices nor flash. :smile: 

Currently I think the code only does (1) and (2). It would be great to add (3) again.

**Comment by katie20** [comment]
I would also like all three steps instead of first two only.

In Version 1.0.6: It supported step (1) and (3). For step (2) user had to manually set it.
In version 1.0.11: It only supports step (1) and step (2).

Is it possible to have all three steps in version 1.0.12? BTW, what happened to version 1.0.7 to 1.0.10?

**Comment by jhuckaby** [comment]
Hmm, alright, I'll get to this as soon as I can.  The logic is getting more and more complex, and I'm going to be slammed with work for a while.

Regarding releases, I started just using tags, not releases:  https://github.com/jhuckaby/webcamjs/tags

Sorry for confusion.

**Comment by katie20** [comment]
Here is the COMPLETE implementation for this logic:

1. check if browser supports navigator.mediaDevices  - This should be easy to check
2. If it does not, then fall back to flash - This should be easy to do (as you implemented in version 1.0.11)
3. If it doesnt support flash, then throw error -  This can be done by following code

`var _flash_installed = ((typeof navigator.plugins !== "undefined" && typeof navigator.plugins["Shockwave Flash"] === "object") || (window.ActiveXObject && (new ActiveXObject("ShockwaveFlash.ShockwaveFlash")) !== false))`

Source: http://stackoverflow.com/questions/8576999/how-to-detect-if-the-browser-support-flash

**So overall pseudo code would be:**

if(navigator.mediaDevices)
 {
    // Browser supports navigator.mediaDevices 
 }
else
 {
 var flash_installed = ((typeof navigator.plugins !== "undefined" && typeof navigator.plugins["Shockwave Flash"] === "object") || (window.ActiveXObject && (new ActiveXObject("ShockwaveFlash.ShockwaveFlash")) !== false))

 if(flash_installed)
 {
   // Browser supports flash
 }
 else
 {
   // Browser neither support mediaDevices  nor flash. Throw error.
  }
}

**Comment by john2014** [comment]
This should work. On line 193, replace the code below

`.catch( function(err) {
setTimeout( function() { self.params.force_flash = 1; self.attach(elem); }, 1 );
});`

with this code:

`.catch( function(err) {`
var is_flash_installed = ((typeof navigator.plugins !== "undefined" && typeof navigator.plugins["Shockwave Flash"] === "object") || (window.ActiveXObject && (new ActiveXObject("ShockwaveFlash.ShockwaveFlash")) !== false))

if(is_flash_installed)
  {    setTimeout( function() { self.params.force_flash = 1; self.attach(elem); }, 1 ); }
else
   {  return self.dispatch('error', err);  }
`});`

This simple code would handle all possible conditions out of the box.

**Comment by jhuckaby** [comment]
There's already a [detectFlash()](https://github.com/jhuckaby/webcamjs/blob/master/webcam.js#L343-L371) function in the library.  I'll use that.

**Comment by jhuckaby** [comment]
Alright, v1.0.12 has just been tagged.  Hopefully this handles all cases.

https://github.com/jhuckaby/webcamjs/releases/tag/v1.0.12

Thanks!
