### ISSUE TITLE
Ability to change the name of the uploaded file object within the options.

### ISSUE THREAD

**Issue by JustinGillespie** [jhuckaby/webcamjs#187]
Currently, there does not seem to be a way to change the uploaded file object name.

(php example) when files are sent to the server, they are bundled under the name 'webcam': $FILES['webcam'] 

I am integrating this into a pre-existing application that also handles uploading an image. All of our files are being uploaded via a $FILES{'photo'] namespace, compressed, resized, etc...

Webcamjs works perfectly within this system, but we have to write extra code to handle the fact that we can't change the uploaded object name to $FILES['photo'] so it handles everything appropriately.

This seems like an easy fix that could use the name 'webcam' as the default, but allow the developer to update that name within the options object.

**Comment by jhuckaby** [comment]
Certainly, I'd be happy to make this configurable.  It'll be in the next release, hopefully this weekend if I can find some time.

**Comment by JustinGillespie** [comment]
That would be fantastic. Thank you for all your hard work on this project.

**Comment by jhuckaby** [comment]
You're welcome!

So as it turns out, this feature is already implemented (it's not documented yet tho).  Just set the `upload_name` parameter to whatever you want (it defaults to `webcam`).  Example:

```js
Webcam.set( 'upload_name', 'photo' );
```

I'll add this to the official documentation in the next release.

Thanks!

**Comment by eddie24** [comment]
quiero saber como guardar mis imagenes tomadas en la camara  en base 64  en la bd en un campo blob ayuda no soy muy habil
