### ISSUE TITLE
Cannot accessible when loading inside the iframe 

### ISSUE THREAD

**Issue by VigneshKumarDR** [jhuckaby/webcamjs#190]
https://www.npmjs.com/package/webcamjs

I installed the above and when i enable the camera using the below command:

            WebCamera.attach('.abc');                
Here .abc is an element inside the iframe.

So it shows the error: WebCam.js error : Could not locate DOM element to attach to.

Any one please suggest.

**Comment by jhuckaby** [comment]
You have to include the script inside the IFRAME.  It must live in the same DOM tree as the target element.
