### ISSUE TITLE
demos not working

### ISSUE THREAD

**Issue by evejweinberg** [jhuckaby/webcamjs#200]
Hi. Thanks for writing this library. 
I'm testing the demos in Chrome, and the photo is all black. The console says this:

Regex

Hide network messages
All
Errors
Warnings
Info
Logs
Debug
Handled
﻿
2
chrome-extension://cbnaodkpfinfiipjblikofhlhlcickei/sideBarIframe/index.html#/main:1 Mixed Content: The page at 'https://pixlcore.com/demos/webcamjs/demos/basic.html' was loaded over HTTPS, but requested an insecure image 'http://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d'. This content should also be served over HTTPS.
chrome-extension://cbnaodkpfinfiipjblikofhlhlcickei/sideBarIframe/index.html#/main:1 Mixed Content: The page at 'https://pixlcore.com/demos/webcamjs/demos/basic.html' was loaded over HTTPS, but requested an insecure image 'http://www.nature.com/favicon.ico'. This content should also be served over HTTPS.

**Comment by positlabs** [comment]
Try using https

**Comment by jhuckaby** [comment]
Here are a few things for you to try:

- Try this HTML5 Webcam test page: https://simpl.info/getusermedia/
- And this one: https://davidwalsh.name/demo/camera.php
- Try this Flash Webcam test page: https://www.onlinemictest.com/webcam-test-in-adobe-flash
- Try jQuery Webcam: http://www.xarg.org/project/jquery-webcam-plugin/
- Try JpegCamera: https://github.com/amw/jpeg_camera

Do any of those work with your webcam?

Also, a few general tips:

- Most browsers now require HTTPS to access the webcam.
- Do not run any WebcamJS demos on your local PC. Flash needs the page to be hosted on a server (with an https:// address) to access the camera.
- Make sure your camera preview size is large enough. Adobe Flash can only show its dialogs if there is enough space. 320x240 or larger.
- Disable ad blockers. Many of them block Flash.
- Disable all your browser extensions. One of them may be interfering with WebcamJS.
- Make sure you have a working webcam with the appropriate drivers.
- Make sure Adobe Flash is up to date.

Hope this helps!

**Comment by evejweinberg** [comment]
thank you so much! I didnt think it was https// issue bc your demo url is https//, but after looking at the other links you sent, i'm realizing that it's an issue with my computer. I have a 2011 MacBook Pro Intel Core i7 with Radeon graphics card. I think there's something about my hardware that doesn't work with webcam.

Anyway, thanks!
