### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by LeoNero** [jhuckaby/webcamjs#204]
Hi. I have the following html:
```
<div class: 'camera-holder' style: "height: 250px; width: 100%;" id="webcam"></div>
```

And my js:
```
function takePhoto() {
    Webcam.snap(function(data_uri) {
         document.getElementById('webcam').innerHTML = '<img src="'+data_uri+'"/>';
    });
}
```

When I execute `takePhoto()`, the photo taken appears on my html, however, the console shows an error: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

And if I try to reuse `takePhoto`, no photo is taken, but the video appears!

How can I solve it?

**Comment by positlabs** [comment]
You html is badly malformed. I'm not sure what the side effects of that would be, but it could be causing this issue.

Try this...

    <div class="camera-holder" style="height: 250px; width: 100%;" id="webcam"></div>

**Comment by positlabs** [comment]
Also, it would be easier to see what the issue is in some live code. Can you create a live example on http://codepen.io ?

**Comment by jhuckaby** [comment]
@LeoNero Also, you are trying to stuff the result (image snapshot) into the same DIV containing the camera, effectively overwriting it.  This will break the library badly, and put it into an undefined state.  Please use a different DIV to hold the result image, not `webcam`.

**Comment by LeoNero** [comment]
@positlabs I'm using Aurelia, and my html is:
```
<div class.bind="stepPhoto == 1 ? 'profile-img--ball' : 'camera-holder'" style.bind="stepPhoto == 1 ? '' : 'height: 250px; width: 100%;'" id="webcam"></div>
```
I made a mistake while writing the html to this question.

@jhuckaby Yeah, I'm doing exactly what you said. I'll try to use a different `div`.

**Comment by LeoNero** [comment]
@jhuckaby Your solution worked. You can close this issue :)

**Comment by jhuckaby** [comment]
Awesome, glad to hear it!
