### ISSUE TITLE
How detect if user has webcam?

### ISSUE THREAD

**Issue by vidiJM** [jhuckaby/webcamjs#206]
Hi,

I have a project that would like know if some user has connected a webcam device before the canvas is loaded.
How can I do it??

thanks a lot!

**Comment by positlabs** [comment]
This is a non-flash solution: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices
```
navigator.mediaDevices.enumerateDevices()
.then(function(MediaDeviceInfo) {
    // check for video devices here
})
```

**Comment by williamsandstrom** [comment]
@positlabs check `MediaDeviceInfo.kind == "videoinput"`

**Comment by positlabs** [comment]
@williamsandstrom yes, like that :)

@vidiJM does this solve your issue? There is probably a method for flash also, but you'd need to modify the swf

**Comment by vidiJM** [comment]
@positlabs @williamsandstrom yes, it solve my issue! thx ;)
