### ISSUE TITLE
Webcam.reset() does not work if Webcam isn't loaded

### ISSUE THREAD

**Issue by Granaweb** [jhuckaby/webcamjs#212]
Hi jhuckaby,
At first I want to thank you for this realy great library.

I remarked an issue on the method Webcam.reset(). If the Webcam isn't loaded, means the Webcam.attach() method produces errors, then the browsers (tested with Chrome and Firefox) will crash when I run Webcam.reset() in the Webcam.on('error', ..) function (see code below).

The reason why I run Webcam.reset() even if the Webcam.attached() failed, is because the error-messages, even if I reset the innerHTML of the results div, the error messages increases each time I try to attach a Webcam. 

Here the piece of code:

```
if($('photoContainer')) {
	document.getElementById('results').innerHTML = '';
	
	Webcam.on( 'load', function() {
		document.getElementById('results').innerHTML += '<p>Library loaded.</p>';
	});
	Webcam.on( 'live', function() {
		document.getElementById('results').innerHTML += '<p>Camera is live.</p>';
	});
	Webcam.on( 'error', function() {
		document.getElementById('results').innerHTML += '<p>Camera couldn\'t be loaded.</p>';
		Webcam.reset();
	});
	Webcam.attach('#photoContainer');
}
```

If this isn't an issue, how can I remove the whole flash object in my photoContainer and reset all error of this Webcam object?

Thank you in advance for your feedback.
Best Regards

**Comment by jhuckaby** [comment]
I'm sorry, but I am having trouble understanding your issue.  Calling `Webcam.reset()` before attaching doesn't produce any errors for me.  Demo:

https://pixlcore.com/demos/webcamjs/demos/click-to-run.html

> how can I remove the whole flash object in my photoContainer and reset all error of this Webcam object?

If `Webcam.reset()` isn't working for you, try clearing out your DIV's contents by passing an empty string to the jQuery `html()` method:

```js
$('#photoContainer').html('');
```

Note that there is a bug in your code above.  You are checking for existence of this object:

```js
if($('photoContainer')) {
```

This is incorrect.  This is looking for an element with a tag name of `<photoContainer>`.  I am assuming this is not what you meant.  Are you missing a `#` hashtag maybe?

**Comment by Granaweb** [comment]
If a device does not have a camera and you try to init the cam by Webcam.attach(), it will open a PopUp with a warning or error message. Then if you have a button, with the Webcam.reset() function to remove the Webcam object (for flash), then you will receive an error.

If you try again and again to do this process (push button init cam, and close cam (Webcam.reset()) then the errors will not been reseted, but the errors will increment.

for your note of:
`if($('photoContainer')) {`
This is prototype js and is the same as in jquery $('#photoContainer').

Sorry for my bad english..
I hope I could explain better the issue.
Here a jsFiddle Link: https://jsfiddle.net/Granaweb/vq1tsdLx/

**Comment by jhuckaby** [comment]
Please try version 1.0.18, and let me know if you are still having this issue.  I still don't quite understand it, but I think my change may have fixed the problem.
