### ISSUE TITLE
capture picture from any webcam live stream

### ISSUE THREAD

**Issue by LuckyDuke23** [jhuckaby/webcamjs#213]
Hi Joseph,

I just registered at GitHub to be able to get in touch with you and to find out whether your webcamjs might be the solution that I am looking for. 

Please apologize that I post my issue here but I could not find any other reliable way to contact you. I am not a developer but have some HTML knowledge to set up individual websites. For my private webcam website, which shows a collection of websites from various locations, I am looking since years for a solution to grab single pictures from any public webcam live stream continuously. Since I don't want active life streams on my website I just want a current still image of a stream which will be updated let's say every 15 minutes. 

Can this be achieved with webcamjs? Thanks in advance. LDuke

**Comment by jhuckaby** [comment]
WebcamJS captures images from a local camera connected directly to the computer via USB.  I think you want something else...

> For my private webcam website, which shows a collection of websites from various locations, I am looking since years for a solution to grab single pictures from any public webcam live stream continuously. 

I don't think WebcamJS can help you with this.  It sounds like you want to grab feeds from webcams on other websites.  That's not what WebcamJS does.  You might try hiring a developer to view the source code of the target websites and figure out how to copy and embed the video streams on your site (better ask permission from the site owners tho).  Some public webcams are just JPEG images that auto-refresh every N minutes.  You might try posting your question on [/r/webdev](https://www.reddit.com/r/webdev/) and see if the experts there can help you.

Good luck!

**Comment by LuckyDuke23** [comment]
Thank you for your quick reply and clarification.
