### ISSUE TITLE
Isolate Webcam.init dependency from Webcam.attach

### ISSUE THREAD

**Issue by dolftax** [jhuckaby/webcamjs#214]
I do not want to display the image being captured. Is there a way to snap without calling attach with a DOM element. Executing Webcam.snap without attaching doesn't seem to work. Error : Webcam not loaded, yet.

**Comment by jhuckaby** [comment]
Move the DOM element offscreen.

**Comment by dolftax** [comment]
@jhuckaby Of course. But that would be an ugly way to do it. Right?

**Comment by jhuckaby** [comment]
@dolftax Flash requires a DOM element to run, so as long as WebcamJS supports Flash fallback, we must always attach to a DOM element.  Also, Flash requires that the user accept permission visually, by clicking inside their DOM object, so it must be visible.

There may be a way to capture the camera "blind" with HTML5 getUserMedia, and you are more than welcome to explore that solution using native JavaScript (no need for a shim library like WebcamJS), but I cannot add a feature that only works with newer browsers.  The whole purpose of WebcamJS is to support older browsers by way of Flash, so I'm tied to that implementation.

Sorry.

**Comment by dolftax** [comment]
@jhuckaby Fair enough. Thanks.
