### ISSUE TITLE
Webcamjs undefined

### ISSUE THREAD

**Issue by tom94zoe** [jhuckaby/webcamjs#216]
Hi, 

I used webcamjs with version 1.0.16 with angular 1.5.9  and everything was fine. 
After the update to 1.0.18 the minified & uglified js is broken. 

Has anyone an idea how to fix this issue? 
A Downgrade  to 1.0.16 or excluding it from the minification process is unacceptable for my employer. 
Thank you  in advance

**Comment by jhuckaby** [comment]
Can you please elaborate?  What do you mean by "broken"?

I tested the 1.0.18 minified version with a variety of web browsers, and webcams, including with and without Flash.  It is working fine for me in all cases.  Please provide more details about the problem you are having, including which browsers and OS versions are affected.

Please provide a test page which shows the bug.

**Comment by jhuckaby** [comment]
I updated all the live demos to use the minified version of the library (v1.0.18), and I still cannot reproduce any errors in any of them.

| Demo Link | Description |
|------|-------|
| [Basic Demo](https://pixlcore.com/demos/webcamjs/demos/basic.html) | Demonstrates a basic 320x240 image capture. |
| [Large Demo](https://pixlcore.com/demos/webcamjs/demos/large.html) | Demonstrates capturing a large 640x480 image, but showing a live preview at 320x240. |
| [Crop Demo](https://pixlcore.com/demos/webcamjs/demos/crop.html) | Demonstrates cropping a 240x240 square out of the center of a 320x240 webcam image. |
| [Large Crop Demo](https://pixlcore.com/demos/webcamjs/demos/crop-large.html) | Demonstrates a large 480x480 square crop, from a 640x480 image capture, with a 240x240 live preview. |
| [HD Demo](https://pixlcore.com/demos/webcamjs/demos/hd.html) | Demonstrates a 720p HD (1280x720) image capture (only supported by some webcams). |
| [SFX Demo](https://pixlcore.com/demos/webcamjs/demos/sfx.html) | Demonstrates a camera shutter sound effect at capture time. |
| [Flash Demo](https://pixlcore.com/demos/webcamjs/demos/flash.html) | Demonstrates forcing Adobe Flash fallback mode. |
| [Freeze Demo](https://pixlcore.com/demos/webcamjs/demos/preview.html) | Demonstrates freezing / previewing a snapshot before saving it. |
| [Mirror Demo](https://pixlcore.com/demos/webcamjs/demos/flip.html) | Demonstrates flipping the image horizontally (mirror mode). |
| [Continuous Demo](https://pixlcore.com/demos/webcamjs/demos/continuous.html) | Demonstrates continuously capturing images. |
| **[Full Combo Demo](https://pixlcore.com/demos/webcamjs/demos/combo.html)** | A full combination demo showcasing all features. |

In order for me to research this issue further, I will need specifics, like the exact error message you are receiving, which OS and browser versions are affected, and a test page that reproduces it.

**Comment by jhuckaby** [comment]
I just released v1.0.19 using the latest version of UglifyJS (v2.7.5) to minify the library.  Not that it should matter, but just trying it to see.  Let me know if the problem persists.

**Comment by tracyIcebreaker** [comment]
Hi, 
Sounds like I'm having the same problem.  Here is the console error:
```
ReferenceError: Webcam is not defined
    at webcam (webcam.directive.js:14)
    at Object.invoke (angular.js:4718)
    at angular.js:7778
    at forEach (angular.js:321)
    at Object.<anonymous> (angular.js:7776)
    at Object.invoke (angular.js:4718)
    at Object.enforcedReturnValue [as $get] (angular.js:4557)
    at Object.invoke (angular.js:4718)
    at angular.js:4517
    at Object.getService [as get] (angular.js:4664)
    at addDirective (angular.js:9494)
    at collectDirectives (angular.js:8677)
    at compileNodes (angular.js:8539)
    at compileNodes (angular.js:8555)
    at compile (angular.js:8442)
    at lazyCompilation (angular.js:8838)
```
Apparently Webcam is no longer a global variable.  I quickly looked through the minified version of the file but can't see why this would be happening.  I'm not using AMD or RequireJS in this project so my code is expecting Webcam on the window.

Thanks!

**Comment by jhuckaby** [comment]
Thank you @tracyIcebreaker.  Can you also confirm that `webcam.js` works fine, and only `webcam.min.js` has the undefined problem?

I've never used Angular, so I don't know how it loads JS libraries.  Are you using a `require()` style statement to load it, or is it a plain `<SCRIPT>` tag in your HTML?

Thanks.

**Comment by tracyIcebreaker** [comment]
Angular should be unrelated in this case - we're using gulp to inject files from bower as script tags into index.html.

**Comment by jhuckaby** [comment]
Okay, understood @tracyIcebreaker.  I will stop focusing on Angular.  Would it be possible for you to confirm if `webcam.js` is working in your application?  Is the problem isolated to `webcam.min.js`?  I am just trying to see if I can isolate the problem to a minification issue, or something in the code itself.  Thanks again for your help.

**Comment by tracyIcebreaker** [comment]
I'm testing it now.  I copied the contents of webcam.js and replaced the min contents as the most expedient test and I'm having the same problem.  I'll test it by linking the file directly too just to be sure.

**Comment by positlabs** [comment]
The module wrapper code isn't crazy complex. You could simply remove it. 

```
if (typeof define === 'function' && define.amd) {
	define( function() { return Webcam; } );
} 
else if (typeof module === 'object' && module.exports) {
	module.exports = Webcam;
} 
else {
	window.Webcam = Webcam;
}
```

I'm not sure how your script injection works, but is it possible that something in your site is defining `define` or `module`? This would prevent it from assigning to the window.

**Comment by jhuckaby** [comment]
Thank you @positlabs, and that is a good point.  I was working off the assumption that WebcamJS v1.0.16 is working fine for everyone (which has the same module wrapper code), but v1.0.18 is somehow broken.  That is what I gleaned from @tom94zoe's initial issue report.

> I used webcamjs with version 1.0.16 with angular 1.5.9 and everything was fine.
> After the update to 1.0.18 the minified & uglified js is broken.

Perhaps @tracyIcebreaker has a different issue altogether.

**Comment by tracyIcebreaker** [comment]
@jhuckaby @positlabs apologies, it looks like it's a different issue altogether.  For some reason webcam.min.js is not being injected into my index.html page.  All the other bower scripts are being injected as per normal, and if I roll back to an earlier version of webcamjs it is injected correctly.  The older version I'd been testing against earlier today was 1.0.6, but I'll test and see which version stops getting injected correctly by my gulp script.

**Comment by jhuckaby** [comment]
Did you say you were using bower @tracyIcebreaker?  Uh oh... at some point I removed the bower.json file from the repository, as I honestly thought no one was using it anymore.  I wonder if that is the problem...

https://github.com/jhuckaby/webcamjs/commit/e32f26dcf5e366e722766d7b3d9b5271518b7d15

Committed January 3, 2017 -- released in v1.0.17.

Oops.

**Comment by tracyIcebreaker** [comment]
That's probably what did it @jhuckaby.  This project has some legacy stuff that should all be converted over to npm but haven't had the time so far.  And ouch, if that's the assumption I better make it a priority.

**Comment by jhuckaby** [comment]
Yikes!  Okay then.  I wonder if @tom94zoe is using bower too.  He is using Angular, so maybe bower comes with that by default?  Let me bring back that file and release v1.0.20 right away.

**Comment by tracyIcebreaker** [comment]
No not by default, probably just something built a while back when bower was still a thing.  If you decide to stop supporting it in the future it may be best to remove it from the bower repository altogether.

**Comment by jhuckaby** [comment]
Oops, didn't realize that commit would auto-close the issue.  Re-opening.

**Comment by jhuckaby** [comment]
Okay, I released v1.0.20 which brings back the `bower.json` file.  @tracyIcebreaker and @tom94zoe could you try your apps again, with this new version?

Thanks, and so sorry about this.

**Comment by tracyIcebreaker** [comment]
@jhuckaby that's fixed it for me, thanks!

**Comment by tracyIcebreaker** [comment]
Now let me go change all this old stuff over to npm...

**Comment by tom94zoe** [comment]
I also use bower. 
It looks like the new version solves the issue. 
Thank you

**Comment by jhuckaby** [comment]
Awesome, thanks @tom94zoe!  And sorry about that.

**Comment by tom94zoe** [comment]
No problem, sorry for belated answer and thank you for your help. 

fyi & angular users: ng-camera uses bower to manage their dependencies. One of them is webcamjs.
