### ISSUE TITLE
Video doesn't fill container in Edge and FireFox

### ISSUE THREAD

**Issue by OasisLiveForever** [jhuckaby/webcamjs#219]
In version 1.0.20 has been changed getUserMedia video initialization from:

this.mediaDevices.getUserMedia({
				"audio": false,
				"video": this.params.constraints || {					
					mandatory: {
					    minWidth: this.params.dest_width,
					    minHeight: this.params.dest_height
					}
				}
			})

to:
this.mediaDevices.getUserMedia({
				"audio": false,
				"video": this.params.constraints || {
					width: this.params.dest_width,
					height: this.params.dest_height
				}
			})

This change causes video to not fill container in Edge and FireFox. On IE 11 and Chrome works correctly.

**Comment by jhuckaby** [comment]
I apologize, I didn't mean to create any issues with this change.  The old `mandatory` syntax is deprecated, and isn't even listed on the MDN documentation anymore.  I thought changing to the new format would be ideal for all browsers.  However, no matter what settings I try now seems to upset one browser or another.  There doesn't seem to be one single setting that satisfies them all.

I will revert the change, and go back to the old `mandatory` thing.
