### ISSUE TITLE
Webcam Dimensions Silent Error

### ISSUE THREAD

**Issue by srm985** [jhuckaby/webcamjs#224]
Greetings!

I'm not sure if this has been discussed previously or maybe it's documented somewhere - but I couldn't find it. I also think the recent issue related to Webcam.freeze() was similar to this. Anyways, I ran into an issue where I set the webcam with a function such as:

`Webcam.set({
   height: 'auto',
   width: 400
});`

Once I attach a webcam, the displayed size of the webcam is 220px high by 400px wide which is defined by the div to which it was attached. I receive no errors for doing this. However, if I call Webcam.snap(), the data_uri returns null. The div holding the webcam is hidden on page load - which is when I set the webcam. Later on, once the div becomes visible, I attached the webcam. I suspected this was causing some issue but I tried to set up the webcam once the div was visible and the problem still persisted. 

I have revised my code to:

`Webcam.set({
   height: 220,
   width: 400
});`

However, it still seems that no matter the dimensions I enter, the webcam box is forced to an aspect ratio of 4/3 with the height always driving the width. For example, setting the height to 220px and the width to 400px yields a webcam that is 220px tall and 295px wide. Is there a way to drop this forced aspect ratio or is it hardware-related? 

Sorry I can't provide a full code example, but I think this should provide the detail required. 

And to summarize my post: 
1.   Ran into a weird error with setting height to auto and width to a static value.
2. Can I get away from the 4/3 aspect ratio of the webcam?

**Comment by jhuckaby** [comment]
Hey @srm985, sorry for the confusion over this.  You'll have to use the [constraints](https://github.com/jhuckaby/webcamjs/blob/master/DOCS.md#custom-user-media-constraints-advanced) system to force your webcam to deliver the aspect ratio you want.

For example if you want an exact aspect ratio, try this:

```js
Webcam.set({
	width: 400,
	height: 220,
	constraints: {
		width: { exact: 400 },
		height: { exact: 220 }
	}
});
```

Note that you cannot use `auto` in the width/height.  It has to be an integer.

**Comment by srm985** [comment]
Thanks for the clarification! And thanks for the great work and quick response. I'll give that a try tomorrow and hopefully that solves my troubles.

**Comment by srm985** [comment]
I can confirm the above solution resolved my issue. Thanks again for taking the time to help!

**Comment by jhuckaby** [comment]
No prob, glad it worked!
