### ISSUE TITLE
Open rear camera in mobile devices .

### ISSUE THREAD

**Issue by s9k96** [jhuckaby/webcamjs#229]
can there be option to select the camera we want to select in mobile devices ?

**Comment by nbulian** [comment]
Hi @s9k96 did you solve this?

**Comment by jhuckaby** [comment]
Hi there!

Check out this document on MDN, it describes how to set the rear camera using a constraint:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

You can pass this to WebcamJS along with the width and height:

```js
Webcam.set( 'constraints', {
	width: 1280,
	height: 720,
	facingMode: { exact: "environment" }
} );
```

More about constraints in the docs here:
https://github.com/jhuckaby/webcamjs/blob/master/DOCS.md#custom-user-media-constraints-advanced

Note that this does **not** work with Adobe Flash fallback -- it only works on browsers that support native HTML5 getUserMedia.

\- Joe
