### ISSUE TITLE
How to force mobile devices to use the rear camera...

### ISSUE THREAD

**Issue by nbulian** [jhuckaby/webcamjs#231]
Hi! Aweson work!

I'm using your library and I want to know if is there a way to use the rear camera in mobile devices?

Thanks!

**Comment by jhuckaby** [comment]
Hi there, thanks!

Check out this document on MDN, it describes how to set the rear camera using a constraint:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

You can pass this to WebcamJS along with the width and height:

```js
Webcam.set( 'constraints', {
	width: 1280,
	height: 720,
	facingMode: { exact: "environment" }
} );
```

More about constraints in the docs here:
https://github.com/jhuckaby/webcamjs/blob/master/DOCS.md#custom-user-media-constraints-advanced

\- Joe
