### ISSUE TITLE
cameraLive event doesn't fire in Safari

### ISSUE THREAD

**Issue by lukele** [jhuckaby/webcamjs#241]
For some reason, Webcam.js has stopped working in the latest version of Safari on El Capitan (Safari v10.1.2).

While the load event is received, the live event no longer fires. Looking through the code, it looks like the ActivityEvent.ACTIVITY event is not firing at any time in Safari now. Would it be possible to use the unmute status in order to fire the "live" event?

Capturing a picture using the snap method still works, but it would be really nice to have the live event back.

(Unfortunately I don't have Adobe Flash, otherwise I would try to fix it myself.)

**Comment by jhuckaby** [comment]
Works fine for me:

<img width="850" alt="screenshot 2017-08-01 19 10 42" src="https://user-images.githubusercontent.com/700765/28854630-312fa304-76ed-11e7-9836-3d96f470d1da.png">

OS X El Capitan 10.11.6
Safari 10.1.2 (11603.3.8)
Adobe Flash 26.0.0.137

I confirmed that the live event fires:
https://pixlcore.com/demos/webcamjs/demos/events.html

<img width="280" alt="screenshot 2017-08-01 19 14 09" src="https://user-images.githubusercontent.com/700765/28854711-9dc6ad50-76ed-11e7-8fc3-9a4d28e094ac.png">

Try reinstalling your Flash player extension maybe?  It can corrupt itself sometimes (I've seen this first hand).  Also, I know it's a total cliché, but restarting your Mac often solves Flash / webcam issues.  The whole Flash extension can get into a bad state and needs a restart sometimes.

Good luck!

\- Joe

**Comment by lukele** [comment]
First off, thank you very for your super fast response.
As it turns out, you where absolutely right – a quick restart fixed the problem.
Out of curiosity, is there any advantage over using the STATUS "unmuted" event?

**Comment by jhuckaby** [comment]
No problem!

> Out of curiosity, is there any advantage over using the STATUS "unmuted" event?

To be honest, I have no idea what that event even is.  Years ago I learned *just enough* ActionScript to write the Flash movie for this project, then I promptly ejected everything from my brain, and took many showers.  If you asked me today, I couldn't even write a "hello world" program in AS 😝 

I'd be happy to change it if that event is better, but I don't even have Adobe Flash installed on my machines anymore.  I'd need someone else to compile the SWF.

**Comment by lukele** [comment]
Ah hehe, me neither that's why I opened the issue in the first place. I wouldn't even thing about using Flash today if it wasn't used by a Wordpress plugin which a customer of mine wanted. Great to see it works now though if the user really has no browser supporting getUserMedia.

Thanks!
