### ISSUE TITLE
This repo is complete garbage, please delete it

### ISSUE THREAD

**Issue by neaumusic** [jhuckaby/webcamjs#254]
Not only do you expect the developer to know the dimensions of the webcam, but you're also scaling with transform after setting the video width and height. This results in completely ridiculous outcomes, and I've wasted hours on yet another useless plugin.

**Comment by positlabs** [comment]
If you're so good, you shouldn't need a plugin.

Submit PRs and quit complaining.

**Comment by jhuckaby** [comment]
@neaumusic You've been reported to GitHub for abuse, and I am blocking you.  I'm sorry this project didn't help you out.  There are many webcam libraries out there.  I hope you find what you are looking for.
