### ISSUE TITLE
Webcam fails in Safari

### ISSUE THREAD

**Issue by splicebison** [jhuckaby/webcamjs#255]
Webcam fails in Safari. This is due to line 319:

`video.src = window.URL.createObjectURL( stream ) || stream;`

This can be replaced with:

`video.srcObject = stream;`

Please note, this isn't tested across all browsers.

**Comment by splicebison** [comment]
To follow up on this, I'd recommend possible something like this (untested):

`
try {
  video.srcObject = stream;
} catch ( error ) {
  video.src = URL.createObjectURL( stream );
}
`

**Comment by mesqueeb** [comment]
I have the same error. It won't work in Safari.
