### ISSUE TITLE
Webcam not loading in Google Chrome Version 64.0.3282.186 

### ISSUE THREAD

**Issue by emanuel1025** [jhuckaby/webcamjs#270]
Webcam.js is not firing either a 'live' event or an 'error' event on attaching to a DOM element. The demo page https://pixlcore.com/demos/webcamjs/demos/events.html does not seem to work as well.

**Comment by fr0z3nfyr** [comment]
Tried on `ver. 66.x` and it works... could be something with browser?!

**Comment by emanuel1025** [comment]
The error had something to do with createObjectURL and I cannot replicate it in Chrome Version  66.0.3359.139.
