### ISSUE TITLE
Safari problem with webcam

### ISSUE THREAD

**Issue by cloudstudio** [jhuckaby/webcamjs#273]
I try this demo in safari, and is not working : 

https://pixlcore.com/demos/webcamjs/demos/basic.html

Is any issue here ? thanks in advance !

**Comment by jhuckaby** [comment]
Sorry, my demo server had an old version of WebcamJS library, which had a bug with Safari 11.  It works now (you may need to clear your browser cache).  Thanks for reporting this!
