### ISSUE TITLE
how to config server(ubuntu) 

### ISSUE THREAD

**Issue by eploentham** [jhuckaby/webcamjs#282]
i test webcam on localhost
it success
but i upload to server 
it can't us webcam

how to i config server 
ubuntu14.04

**Comment by jhuckaby** [comment]
HTTPS

**Comment by eploentham** [comment]
thank you
but i us intranet(in office)
there is no need to us https

how to other solution to correct this issue

**Comment by jhuckaby** [comment]
Browsers require HTTPS for webcam access, if not on localhost.

**Comment by eploentham** [comment]
thank you
