### ISSUE TITLE
webcam.js Error: Webcam is not loaded yet -- just started in Chrome 71.0.3578.80

### ISSUE THREAD

**Issue by debnusbaum** [jhuckaby/webcamjs#285]
Webcam.js has been working flawlessly for years.
Today, 12/11/2018, started getting the subject error message and webcam no longer working.
Only affects Chrome 71.0.3578.80 and beta from what I can see.

Works fine in prior version of Chrome (70.0.3538.110)

Works fine in Edge.  Haven't tried all browsers. 

Site using HTTPS://

**Comment by debnusbaum** [comment]
Closing Issue.
Was using webcam.js level prior to 1.0.25.
1.0.25 seems to resolve the problem.

**Comment by Rishishah97** [comment]
So Finally, What's the Solution ??
in what files you changed the code ?
please mention the file name in detail changes asap !!

**Comment by positlabs** [comment]
>1.0.25 seems to resolve the problem.

Are you using the most up to date version?

**Comment by Rishishah97** [comment]
Yes  please refer the attachment for the Error i get and Chrome Version
