### ISSUE TITLE
HD Demo

### ISSUE THREAD

**Issue by sugh3147** [jhuckaby/webcamjs#36]
HD Demo does not work for me.

**Comment by whodeee** [comment]
The issue is with setting the media constraints - you have to do something like this:
```
var hdConstraints = {
  video: {
    mandatory: {
      minWidth: 1280,
      minHeight: 720
    }
  }
};

navigator.getUserMedia(hdConstraints, successCallback, errorCallback);
```

**Comment by jhuckaby** [comment]
Ah, thank you very much!  I added this in v1.0.1, and it seems to work fine for me now.

http://pixlcore.com/demos/webcamjs/demos/hd.html

- Joe
