### ISSUE TITLE
webcam.js, could not access webcam in chrome and opera.

### ISSUE THREAD

**Issue by ray86** [jhuckaby/webcamjs#37]
having issues with chrome and other browsers when users reject the broswer dialog the very first time. it keeps displaying webcam.js error everytime the page is reloaded. please, anyway i can work around that?
![capture-20141014-053232](https://cloud.githubusercontent.com/assets/9213837/4628951/559d8fc8-539e-11e4-8f74-59c037cf488e.png)

**Comment by chinmay235** [comment]
Hi,
I am trying to get my webcam in chrome browser.  Here is my stackoverflow link - http://stackoverflow.com/questions/38388358/webcam-js-not-working-in-chrome-browser please give me any solution.

**Comment by jhuckaby** [comment]
@chinmay235 Your website must be hosted with HTTPS (SSL).  **It does not work with HTTP**.  This is a limitation of the Chrome browser.

**Comment by jokerosky** [comment]
@jhuckaby  And what can i do  if i want to handle this error by myself inside try-catch block ? 
for example:
                    try {
                        Webcam.attach('#webcamVideo');
                    }
                    catch (exp) {
                        console.error(exp);
                        $Error("Webcam access error! Try to use https:// protocol");
                    }

**Comment by jhuckaby** [comment]
@jokerosky The `attach()` method does not throw, so there's nothing to catch with a try/catch.  Instead, add a listener for the `error` event:

```js
Webcam.on( 'error', function(err) {
	// an error occurred (see 'err')
} );

Webcam.attach('#webcamVideo');
```

**Comment by jokerosky** [comment]
@jhuckaby  will it prevent alerts like the one  in first post of this topic?

**Comment by jhuckaby** [comment]
@jokerosky Yes.

**Comment by Marlysson** [comment]
@jhuckaby Exactaly what I wanted to do .. prevent show alert when webcam are disabled.

Do there are some way to define custom errors on lib Webcam? And not handle event error..

Because I saw the ```dispatch``` method and them throw the alert error that I want prevent ..

Just exists this way to remove alert?

**Comment by ArunEdathadan** [comment]
One browser at  a time

**Comment by VutheaKorms** [comment]
please include this codes 
worked Firefox and Chrome 
<script type="text/javascript">
        function captureWebCam() {
            Webcam.set({
                width: 600,
                height: 450,
                image_format: 'png',
                jpeg_quality: 90
            });
            Webcam.attach('#my_camera');
        }
</script>

**Comment by fraserredmond** [comment]
Anyone getting this in 2019 - URL.createObjectURL has now been deprecated in Chrome 71.

This worked for me: https://stackoverflow.com/a/53821674/151503

**Comment by 1108Joyu** [comment]
Brother it is not working b'coz if you are using one webcam in different two application on same time at that time you facing this issue. Please, Close your unnecessary application.

**Comment by pemakanwortel** [comment]
Webcam.js Error: Could not access webcam: OverconstrainedError:  OverconstrainedError
how to fix this ?
