### ISSUE TITLE
Not working in Firefox and Internet Explorer

### ISSUE THREAD

**Issue by emisand** [jhuckaby/webcamjs#4]
I have been trying webcamjs and it works perfectly in Google Chrome.
But when I tried it in Firefox and Internet Explorer it does not work at all.

Tried even using your demo url and it doesn't work.
If I click at Take Snapshot I get: "Webcam.js Error: Webcam is not loaded yet"

So this is only working in Chrome for now.

**Comment by yogendrakarekar** [comment]
still not working in IE11. please help, showing error, webcam.js Error : could not access webcam.
please help

**Comment by jhuckaby** [comment]
@yogendrakarekar I'm sorry, I cannot reproduce your issue.  WebcamJS is working just fine on my Win7/IE11 machine.  Screenshot below:

![screenshot 2015-10-08 19 45 54](https://cloud.githubusercontent.com/assets/700765/10385112/81b6e0de-6df9-11e5-9dd4-cea850126d53.png)

Here are a few things for you to try:

* Remember, you must have Adobe Flash for IE 11 to work.
* Do not try any WebcamJS demos running on your local PC's Hard Disk.  Flash needs the page to be hosted on a remote server (with an http:// address) to access the camera.
* Make sure your camera preview size is large enough.  Adobe Flash can only show its dialogs if there is enough space.  320x240 or larger.
* Disable ad blockers.  Many of them block Flash.
* Disable all your browser extensions.  One of them may be interfering with Flash.
* Make sure you have a working webcam with the appropriate drivers.
* Make sure IE and Windows are both up to date.
* Make sure Adobe Flash is up to date.
* Try jQuery Webcam: http://www.xarg.org/project/jquery-webcam-plugin/
* Try JpegCamera: https://github.com/amw/jpeg_camera

Good luck, and sorry I could not help.

**Comment by yogendrakarekar** [comment]
@jhuckaby dats k, i'll look into it. actually the thing is dat it is also not asking me for adobe flash updation. even not giving me the error webcam error: could not run webcam.
but anyways thanks for help

**Comment by yogendrakarekar** [comment]
@jhuckaby when I open your demo page in ie11 it works but when i try to implement it on localhost it does not works. it does not gives a popup for adobe or webcam.js error, shows nothing, just a blank div

**Comment by jhuckaby** [comment]
Read what I said above:

- Do not try any WebcamJS demos running on your local PC's Hard Disk. Flash needs the page to be hosted on a remote server (with an http:// address) to access the camera.
