### ISSUE TITLE
Feature Request: camera choice

### ISSUE THREAD

**Issue by whimsicaldreamer** [jhuckaby/webcamjs#41]
I was hoping if i could use this library on a mobile website and it would open up the rear camera/front camera according to users choice, it would be great. Then i wont be required to use jquery mobile library.

**Comment by rafverhaert** [comment]
Following code gives me an error because cameraID is undefined.
Webcamjs shows me the front camera but i need te camera on the back of my tablet

// selecting camera device
if (Webcam.cameraIDs.length > 1) {
Webcam.cameraID = 1;
}

**Comment by cyphunk** [comment]
@rafverhaert you have to use the fork version of the code which has the cameraid's array https://github.com/carvilsi/webcamjs/blob/master/webcam.js#L72
