### ISSUE TITLE
Flash snapshot doesn't work

### ISSUE THREAD

**Issue by poloop** [jhuckaby/webcamjs#49]
With the basic demo on Safari on mac, it seems notification from flash are not received because the live parameter is never true.
I have an other issue with IE8 which doesn't support canvas to render snapshot.

**Comment by jhuckaby** [comment]
Below is a screenshot showing WebcamJS working just fine in Safari on Mac using Flash.  You must have some kind of Flash or Plugin blocking extension, or perhaps Safari's own "Stop plug-ins to save power" option is enabled, in Prefs / Advanced.

As for IE 8, it is not supported, sorry.  IE 9 or above.

![screenshot 2015-01-16 09 01 03](https://cloud.githubusercontent.com/assets/700765/5780307/56933d56-9d5e-11e4-89ea-6918613c3177.png)
