### ISSUE TITLE
Video to Canvas

### ISSUE THREAD

**Issue by pbrickner** [jhuckaby/webcamjs#54]
Is it possible for this to have the video go directly to a canvas?  I see that the snap shots can be put to canvas but can the video?  I have tried but been unsucccessful.  Thanks!

**Comment by jhuckaby** [comment]
Hey pbrickner,

Well, unfortunately WebcamJS is designed more for producing JPEG or PNG still frames.  It doesn't really have any video support.  However, you can call setInterval() to take frames every 1/60 of a second and then render it to your own canvas.  The latter is shown in this section of the docs:

https://github.com/jhuckaby/webcamjs#snapping-a-picture

So basically setup your own canvas on the page, then setup a setInterval() which calls Webcam.snap() and use the instructions in the docs to copy the pixels to your canvas.

Good luck!

Also, it should be noted that you don't really need WebcamJS for this.  You can simply use the HTML5 getUserMedia API directly, and then render the video frames to a canvas.  Detailed explanation here:

http://html5hub.com/using-the-getusermedia-api-with-the-html5-video-and-canvas-elements/

- Joe
