### ISSUE TITLE
Problem with visualStudio

### ISSUE THREAD

**Issue by szagarella** [jhuckaby/webcamjs#56]
Hello and congrats for your library. It's very good.
My problem is that library doesn't work with WebBrowser in VisualStudio. My browser is IE10 and, after add excanvas.js, it works perfectly: but, when I add the content in a webBrowser inside VisualStudio, it crashed. 
The error is generic: "SCRIPT ERROR" in file webcam.js.
Do you know what cuold be the problem?

Thanks 

[UPDATE]: Analyze the code, the error break out at block 'getMovie' [line 284]. Maybe the error is similat to 'Object doesn't support property or method '_snap''. It seams not find the callback.
Can you help me?

**Comment by jhuckaby** [comment]
Looks like the web browser in Visual Studio doesn't support Flash.  Sorry, I don't use Visual Studio so I have no other ideas.  Good luck, and sorry.
