### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by mani541** [jhuckaby/webcamjs#60]
The image is not getting captured, In IE 11. It works fine in other browsers.
The error is

SCRIPT:438 Object doesn't support property or method '_snap'

**Comment by jhuckaby** [comment]
That error means there is a problem with your Adobe Flash Player Plugin, which is required for the library to work in IE.  Please make sure you are running the latest version (v17.0.0.134 as of this writing).

Here is a screenshot showing it working in IE 11:

![screenshot 2015-03-27 22 31 14](https://cloud.githubusercontent.com/assets/700765/6879923/4a1b4798-d4d2-11e4-8166-3fe40bc791b9.png)

Good luck!

- Joe
