### ISSUE TITLE
Custom events not working for Flash (IE) fallback

### ISSUE THREAD

**Issue by LiamChapman** [jhuckaby/webcamjs#61]
Firstly, thanks for all your hardwork on this plugin! It's really great. It works well. However, I've noticed in IE when using the fallback it doesn't fire the custom events mentioned here:

https://github.com/jhuckaby/webcamjs#custom-events

On chrome and getusermedia supported browsers I'm using the live event to fire events to change the look and feel so I know the camera is ready. If I do this on IE, it doesn't do it all. Is there common fix for this? Or is this a feature that is not supported for the Flash fallback?

(I tested this in IE11 btw)

Thanks.

**Comment by jhuckaby** [comment]
Sorry man, I have no idea why custom events are not working for you in IE 11.  This has been fully tested, and they work for me.  Here is a screenshot showing them working right now (I'm printing them to the box in the top-right corner):

![screenshot 2015-03-27 22 31 14](https://cloud.githubusercontent.com/assets/700765/6879927/8b0c8c1c-d4d2-11e4-9355-9b2a294b9841.png)

Both the "load" and "live" events are firing for me in IE 11 (Windows 7) with a Logitech c920 webcam.

This demo can be found here:
http://pixlcore.com/demos/webcamjs/demos/events.html

Can you please make sure you are running the latest Adobe Flash Player Plugin (v17 as of this writing)?  This is required for the library to work in IE.

Good luck, and sorry if this did not help.  Check your developer tools to see if IE is throwing a JavaScript error or something.

- Joe
