### ISSUE TITLE
flip_x should always be disabled when asking permissions

### ISSUE THREAD

**Issue by positlabs** [jhuckaby/webcamjs#64]
For readability ;)

![screen shot 2015-04-07 at 5 58 31 pm](https://cloud.githubusercontent.com/assets/1918844/7036946/d9caf868-dd4f-11e4-9622-72438eee5b0e.png)

**Comment by jhuckaby** [comment]
That's really strange, I thought I handled all those cases.  Can you tell me how you reproduced this?  Did you use one of the built-in demos?  What browser / OS?

**Comment by positlabs** [comment]
It only happens after the first time permissions are granted. e.g. open camera, grant permissions, accept photo, open camera, see flipped permissions dialog. I'm testing on chrome latest.

**Comment by jhuckaby** [comment]
Darn, I am unable to reproduce it from here.  It never re-asks me for permissions after the first photo, and Chrome uses getUserMedia, not Flash.

I'll keep trying to figure it out tho.

**Comment by positlabs** [comment]
Oh hmm. I'll keep testing across browsers. I'm using `force_flash` on Chrome, for now.

**Comment by jhuckaby** [comment]
Ah, I see.  I don't think I've tested the combination of both `force_flash` and `flip_horiz` on Chrome.  I'll do that as soon as I can, and try to correct the bug.  Thanks!

**Comment by jhuckaby** [comment]
Okay, let me know if this fixes it.

https://github.com/jhuckaby/webcamjs/commit/fa2514fa4b48aea707d5c6ffed0705795c7ae8d2

- Joe

**Comment by positlabs** [comment]
Do I need to call `reset` manually? I don't see it referenced anywhere else.

**Comment by jhuckaby** [comment]
Ah, I was assuming you were testing on a page that called `reset()`, because I cannot figure out any other way that Flash could have showed you the permissions dialog again after the initial time.  This was a shot in the dark fix at best.

If you aren't calling reset, then the bug is elsewhere.

**Comment by mani541** [comment]
Hello huckaby,
                     This is third mail from me regrding the issue, I have
already sent lines of my code to work in IE and safari. The IE is not able
to load the flash content when loading the page. As far the demo you have
shown, please try webcam.on(error) or live, function triggered once the
user presses allow or deny in the flash dialogue box. I am not getting the
image captured in IE and safari. after webcam.on(live) function, In all the
other browsers, html5 getusermedia is supported. I have tried with firefox
17, which goes with flash fallback, and it worked fine with the image
capture. Please, let me know how can I rectify this error. I really
appreciate your good work.

**Comment by positlabs** [comment]
@mani541 I think you have the wrong thread.

**Comment by positlabs** [comment]
Aha! I found it! Flash ask permission again if the containing div is set to `display: none`. It automatically disables the webcam if the swf is hidden from view. Tricky!

Maybe there is some way to detect this on the flash side?

**Comment by mani541** [comment]
Webcam.set(
{
width: 320,
height: 240,
image_format: 'jpeg',
jpeg_quality: 90,

});
Webcam.attach( '#cam' );
Webcam.on( 'error', function(err)
{
error = true;
alert("We could not access the webcam. Please allow the Webcam Access to
Proceed");
Webcam.attach( '#cam' );
});
Webcam.on( 'live', function()
{
error = false;
$('#cam').hide();
captureimage();
});
I have just loaded the js file, and tried setting eith above code, but I
couldn't make this work in IE and safari. Do you have any suggestion to
make?

**Comment by positlabs** [comment]
@mani541, if you file an issue here https://github.com/jhuckaby/webcamjs/issues it will be much easier to help you. Currently, you're hijacking a thread about something totally unrelated.

**Comment by mani541** [comment]
Thanks for your suggestion. I just overlooked a mail, and sent it to you.I
have no intention to hijack your thread.

**Comment by jhuckaby** [comment]
Ah, good find @positlabs!

I have no idea how to detect that from the Flash side.  In JavaScript, I believe `Webcam.container.offsetWidth` will be 0 if any parent element is collapsed with `display:none`, but I don't know exactly *when* to act on this information.  Meaning, I have no idea when you restore the DIV, and Flash shows you the permissions dialog the second time -- there is no notification event.

Would it be possible to have you call `Webcam.unflip()` when you hide the containing DIV?  This will reset the styles and remove the CSS transform that mirrors it horizontally.

**Comment by positlabs** [comment]
Yep, that does the trick. I don't think this is really worth addressing in webcamjs since it's such an edge case, so I'll close the ticket. Thanks!

**Comment by jhuckaby** [comment]
Cool, thanks!
