### ISSUE TITLE
Transparent windowless swf

### ISSUE THREAD

**Issue by positlabs** [jhuckaby/webcamjs#65]
It would be useful to have a transparent windowless swf so the background during permissions phase can be easily customizable with html. 

https://helpx.adobe.com/flash/kb/transparent-background-swf-file.html

P.S. Sorry for the flood of issues. I can probably make some PRs for some of these.

**Comment by positlabs** [comment]
Actually I'm not sure how to do this. Tried setting wmode to "transparent" but it didn't work. Any ideas?

**Comment by jhuckaby** [comment]
I'm sorry, I have no idea what the Flash `wmode' thing does.  Looks like WebCamToy has figured it out tho: http://webcamtoy.com/app/

**Comment by positlabs** [comment]
I'm gonna close this. Not super important
