### ISSUE TITLE
Facing issue in firefox

### ISSUE THREAD

**Issue by ErNarendra** [jhuckaby/webcamjs#71]
Hi, 
i use demo but i got error in alert box when i open demo in firefox in chrome working fine.
This is the error :- "Webcam.js Error: Could not access webcam"

if i use userMedia: true then working on chrome but not in firefox.
if i use userMedia: false then working on firefox but not in chrome.
so please tell me what is this option and what i have to do?

Please help on this ASAP.
Thanks,

**Comment by ErNarendra** [comment]
Hey,
Got it i just remove navigator.mozGetUserMedia and window.mozURL from init: function() and set userMedia: true now i can open it in mozila firefox and chrome.
Now please tell me this is right or it make some issue on live?
Thanks,

**Comment by jhuckaby** [comment]
Sounds like you have a webcam that only works in Flash.  Try setting "`force_flash`" parameter to true.

http://pixlcore.com/demos/webcamjs/demos/flash.html

**Comment by ErNarendra** [comment]
Hi,
Thanks for your reply, please help on one more thing.
i set force_flash: true,
Your given link is work on some of my system but not on all system, i remove all cache but same thing happen with my demo.
Thanks.

**Comment by jhuckaby** [comment]
Video is not supported, sorry.  If you want to capture video, please check out [WebRTC](http://www.webrtc.org/): 

http://www.webrtc.org/

I am sorry the library doesn't work on all your systems.  Please try [jQuery Webcam](http://www.xarg.org/project/jquery-webcam-plugin/) -- you might have better luck with that library:

http://www.xarg.org/project/jquery-webcam-plugin/

Good luck to you.

**Comment by appnuri** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

appnuri@appnuri.kr 님께 보내신 메일 <Re: [webcamjs] Facing issue in firefox (#71)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
