### ISSUE TITLE
Webcam.on() only allows a single handler to be bound

### ISSUE THREAD

**Issue by scurker** [jhuckaby/webcamjs#73]
I discovered this when trying to bind multiple event handler functions to a single event, but it seems that the current version only allows a single event to be bound at a time.

```javascript
Webcam.on('live', function() {
  // do something here with the camera
});

...

// Located somewhere else in code
Webcam.on('live', function() {
  // do something else with the camera
});
```

Only the most recently set handler will actually fire when the event is created. This seems contrary to how events are typically handled in Javascript - and it would be nice if the could could handle multiple events being attached.

**Comment by jhuckaby** [comment]
You're absolutely right, Jason.  I'll fix this in the next release.  Thanks!

**Comment by scurker** [comment]
Just attached a pull request, but not sure if that's the direction you want to go. I noticed that the dispatcher also allows for arrays and global functions to be set.

**Comment by positlabs** [comment]
Here's a simple events thing I wrote a while back. https://gist.github.com/positlabs/7646311

**Comment by jhuckaby** [comment]
Thanks @scurker and @positlabs!  I may use some or both of these solutions :)

**Comment by scurker** [comment]
@positlabs's approach would be more beneficial if you wanted to unload event handlers as well. I haven't had a need for it yet, but I imagine there may be instances where someone would be interested.

**Comment by jhuckaby** [comment]
Fixed in https://github.com/jhuckaby/webcamjs/commit/a7b886e3532a13580072a3fc21e260a44ff33edd

Thanks guys!

**Comment by scurker** [comment]
:+1: Thanks for hoping for this so quick!
