### ISSUE TITLE
Timestamp feature on snapshot

### ISSUE THREAD

**Issue by ugran** [jhuckaby/webcamjs#78]
Hello,

First of all thank you for maintaining such a great project.

Yesterday I was checking on the webcamJS and I liked it very much.

I though about a scenario where one needs to check time of snapshot taking.

Will it be hard to add a timestamp to an image without much of image processing? With only using javascript?

**Comment by jhuckaby** [comment]
Thank you.

Yes, you can accomplish this with JavaScript and the Canvas object.  Check out the docs for how to get access to the raw canvas object used to capture the camera frames (it's passed to your callback when calling `snap()`), then you can render text onto it using Canvas `fillText()`:

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

Good luck!
