### ISSUE TITLE
Provide a package.json and publish it to npm

### ISSUE THREAD

**Issue by binarykitchen** [jhuckaby/webcamjs#93]
For the nodejs folks, thanks

**Comment by jhuckaby** [comment]
I thought npm was for server-side Node.js libraries.  WebcamJS is 100% client-side.  Is that.... okay?  I mean, it has a bower.json file for Bower.  Does it also need to be on npm?

**Comment by binarykitchen** [comment]
haha no, not true - who said that? a lot has changed and you'll even find jQuery on npm.

yes, please publish to npm. many noders do not use bower at all.

**Comment by jhuckaby** [comment]
Oh, okay.  I honestly didn't know.  NPM stands for "Node Package Manager" so I thought it was for Node modules only.  Okay, I'll publish WebcamJS there :)

**Comment by binarykitchen** [comment]
nah, it's not an abbreviation anymore but an acronym now, see https://docs.npmjs.com/misc/faq

**Comment by jhuckaby** [comment]
HAHAHAHAAH!  What a great explanation.  I love those guys.  Thanks @binarykitchen!  I'll get this published tonight.

**Comment by jhuckaby** [comment]
Here you go:

https://www.npmjs.com/package/webcamjs

\- Joe

**Comment by binarykitchen** [comment]
thanks - i am sure i ll be in touch with you soon regarding www.videomail.io ...

**Comment by YyMn192** [comment]
我想问一下这个怎么在vue中使用   webcam is not undefined

**Comment by binarykitchen** [comment]
english please

**Comment by gaojiankang** [comment]
how to I use in vue freamwork?
