### ISSUE TITLE
Event for when the Flash "Allow" button is pressed

### ISSUE THREAD

**Issue by binarykitchen** [jhuckaby/webcamjs#96]
Hello there

I've been looking for a callback in the JS code which is triggered when the user allowed Flash to be run. That "Allow" button you know.

What's the callback or the event name for that?

Thx!

**Comment by positlabs** [comment]
I believe you can use the `live` event to listen for when this happens.

**Comment by binarykitchen** [comment]
Great, thanks. Maybe this should be documented?

**Comment by jhuckaby** [comment]
Added clarification to the docs:

https://github.com/jhuckaby/webcamjs/blob/master/README.md#custom-events

Thanks.

**Comment by binarykitchen** [comment]
great!
