### ISSUE TITLE
Have a slim version with the flash fallback and some JS code

### ISSUE THREAD

**Issue by binarykitchen** [jhuckaby/webcamjs#97]
For my other experiment, I need parts of webcamjs, but not the whole code. To avoid an unnecessary  fork and clustering, I wonder if you could split some code into a smaller npm module?

Just the flash fallback and some JS code for its event handling. So that I can reuse it somewhere else in another getUserMedia related project which already somes with it's own getUserMedia code.

And anyway, it's always good to split code into smaller reusable modules.

**Comment by binarykitchen** [comment]
Ping?

**Comment by jhuckaby** [comment]
Hey @binarykitchen,

I'm sorry, but I really don't want to split the library up.  It is important to me that I can include one single JS file, straight from the repo, and it all just works.  I don't want to have to use npm to piece it together.  

You are of course more than welcome to take any parts you want and create your own module, with just the Flash piece.  It hasn't changed in years, so I don't think there is any risk of it getting modified from under you.  As long as Flash sticks around (which will probably be at least another year) I am confident the webcam code will still work with it.

Good luck, and sorry!

**Comment by binarykitchen** [comment]
I understand. Still this is doable, and having pieces through npm modules is better. Modularity is awesome. And to have one single JS file, browserify is the answer.

Don't like the idea to fork and make my own modules. I ll think of something else then.

**Comment by jhuckaby** [comment]
I apologize.  I understand modularity is great, but I see this as one single module.  And I really don't want to have to use npm or browserify to use it.  I like having it exist as one plain JS file.

Remember, GitHub has a fork button 😊 -- you can change this library however you want 😊 

Sorry, and best of luck to you.

**Comment by binarykitchen** [comment]
No problem, no hard feelings :)
